const users = [
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    email: 'admin@smartedu.com',
    password: '123456',
    name: '系统管理员',
    avatar: '/placeholder-user.jpg',
    role: 'admin',
    status: 'active',
  },
  {
    id: 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22',
    email: 'teacher@smartedu.com',
    password: '123456',
    name: '张教授',
    avatar: '/placeholder-user.jpg',
    role: 'teacher',
    status: 'active',
  },
  {
    id: 'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380a33',
    email: 'student@smartedu.com',
    password: '123456',
    name: '小明同学',
    avatar: '/placeholder-user.jpg',
    role: 'student',
    status: 'active',
  },
];

const categories = [
  {
    id: 'd1eebc99-9c0b-4ef8-bb6d-6bb9bd380a01',
    name: '计算机科学',
    slug: 'computer-science',
    description: '涵盖计算机基础知识、编程语言、软件工程等',
    icon: 'computer',
    sort_order: 1,
  },
  {
    id: 'd1eebc99-9c0b-4ef8-bb6d-6bb9bd380a02',
    name: '数学',
    slug: 'mathematics',
    description: '高等数学、线性代数、概率论等数学课程',
    icon: 'calculator',
    sort_order: 2,
  },
  {
    id: 'd1eebc99-9c0b-4ef8-bb6d-6bb9bd380a03',
    name: '人工智能',
    slug: 'artificial-intelligence',
    description: '机器学习、深度学习、自然语言处理等AI课程',
    icon: 'brain',
    sort_order: 3,
  },
  {
    id: 'd1eebc99-9c0b-4ef8-bb6d-6bb9bd380a04',
    name: '网络工程',
    slug: 'network-engineering',
    description: '计算机网络、通信原理、网络安全等',
    icon: 'globe',
    sort_order: 4,
  },
  {
    id: 'd1eebc99-9c0b-4ef8-bb6d-6bb9bd380a05',
    name: '软件工程',
    slug: 'software-engineering',
    description: '软件开发方法论、项目管理、软件测试',
    icon: 'code',
    sort_order: 5,
  },
  {
    id: 'd1eebc99-9c0b-4ef8-bb6d-6bb9bd380a06',
    name: '数据科学',
    slug: 'data-science',
    description: '数据分析、数据挖掘、大数据技术',
    icon: 'database',
    sort_order: 6,
  },
];

const courses = [
  {
    id: 'e1eebc99-9c0b-4ef8-bb6d-6bb9bd380a01',
    title: '高等数学',
    slug: 'higher-mathematics',
    description: '涵盖微积分、微分方程、级数等核心内容',
    teacher_id: 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22',
    category_id: 'd1eebc99-9c0b-4ef8-bb6d-6bb9bd380a02',
    cover_image: '/placeholder.jpg',
    hours: 64,
    chapters_count: 12,
    tags: ['必修', '基础'],
    difficulty: 'medium',
    is_published: true,
  },
  {
    id: 'e1eebc99-9c0b-4ef8-bb6d-6bb9bd380a02',
    title: '数据结构与算法',
    slug: 'data-structures-algorithms',
    description: '学习线性表、树、图等数据结构及排序搜索算法',
    teacher_id: 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22',
    category_id: 'd1eebc99-9c0b-4ef8-bb6d-6bb9bd380a01',
    cover_image: '/placeholder.jpg',
    hours: 56,
    chapters_count: 10,
    tags: ['必修', '核心'],
    difficulty: 'medium',
    is_published: true,
  },
  {
    id: 'e1eebc99-9c0b-4ef8-bb6d-6bb9bd380a03',
    title: '人工智能导论',
    slug: 'introduction-to-ai',
    description: '探索AI基础理论、机器学习与深度学习入门',
    teacher_id: 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22',
    category_id: 'd1eebc99-9c0b-4ef8-bb6d-6bb9bd380a03',
    cover_image: '/placeholder.jpg',
    hours: 52,
    chapters_count: 11,
    tags: ['选修', '热门'],
    difficulty: 'hard',
    is_published: true,
  },
  {
    id: 'e1eebc99-9c0b-4ef8-bb6d-6bb9bd380a04',
    title: '计算机网络',
    slug: 'computer-networks',
    description: '深入理解TCP/IP协议栈、网络架构与应用',
    teacher_id: 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22',
    category_id: 'd1eebc99-9c0b-4ef8-bb6d-6bb9bd380a04',
    cover_image: '/placeholder.jpg',
    hours: 48,
    chapters_count: 8,
    tags: ['必修', '核心'],
    difficulty: 'medium',
    is_published: true,
  },
  {
    id: 'e1eebc99-9c0b-4ef8-bb6d-6bb9bd380a05',
    title: '操作系统原理',
    slug: 'operating-system-principles',
    description: '进程管理、内存管理、文件系统与I/O系统',
    teacher_id: 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22',
    category_id: 'd1eebc99-9c0b-4ef8-bb6d-6bb9bd380a01',
    cover_image: '/placeholder.jpg',
    hours: 48,
    chapters_count: 9,
    tags: ['必修', '核心'],
    difficulty: 'hard',
    is_published: true,
  },
];

const chapters = [
  {
    id: 'f1eebc99-9c0b-4ef8-bb6d-6bb9bd380a01',
    course_id: 'e1eebc99-9c0b-4ef8-bb6d-6bb9bd380a01',
    title: '第一章：极限与连续',
    description: '理解极限的概念，掌握连续函数的性质',
    sort_order: 1,
    is_published: true,
  },
  {
    id: 'f1eebc99-9c0b-4ef8-bb6d-6bb9bd380a02',
    course_id: 'e1eebc99-9c0b-4ef8-bb6d-6bb9bd380a01',
    title: '第二章：导数与微分',
    description: '学习导数的定义、求导法则及其应用',
    sort_order: 2,
    is_published: true,
  },
  {
    id: 'f1eebc99-9c0b-4ef8-bb6d-6bb9bd380a03',
    course_id: 'e1eebc99-9c0b-4ef8-bb6d-6bb9bd380a02',
    title: '第一章：线性表',
    description: '顺序表、链表的概念与实现',
    sort_order: 1,
    is_published: true,
  },
  {
    id: 'f1eebc99-9c0b-4ef8-bb6d-6bb9bd380a04',
    course_id: 'e1eebc99-9c0b-4ef8-bb6d-6bb9bd380a02',
    title: '第二章：栈与队列',
    description: '栈和队列的特性与实现',
    sort_order: 2,
    is_published: true,
  },
];

const aiRoles = [
  {
    id: 'a1eebc99-9c0b-4ef8-bb6d-6bb9bd380b01',
    name: 'AI 学霸导师',
    slug: 'ai-tutor',
    subtitle: '你的专属学习助手',
    description: '可以帮你解答课程问题、讲解知识点、辅导作业',
    system_prompt: '你是一位耐心、知识渊博的学业导师，擅长用通俗易懂的语言解释复杂的概念。',
    greeting: '你好！我是你的AI学习导师，有什么学习上的问题都可以问我哦！',
    icon: 'GraduationCap',
    color: '#3B82F6',
    is_active: true,
    sort_order: 1,
  },
  {
    id: 'a2eebc99-9c0b-4ef8-bb6d-6bb9bd380b02',
    name: '编程大师',
    slug: 'code-master',
    subtitle: '代码问题终结者',
    description: '擅长各类编程语言，帮助你debug、优化代码',
    system_prompt: '你是一位经验丰富的程序员，精通多种编程语言和框架，善于帮助初学者理解编程概念。',
    greeting: '你好！我是编程大师，遇到代码问题了吗？让我来帮你看看！',
    icon: 'Code',
    color: '#10B981',
    is_active: true,
    sort_order: 2,
  },
  {
    id: 'a3eebc99-9c0b-4ef8-bb6d-6bb9bd380b03',
    name: '英语口语教练',
    slug: 'english-coach',
    subtitle: '提升你的英语水平',
    description: '陪你练习英语对话，纠正发音和语法',
    system_prompt: '你是一位友善的英语口语教练，擅长引导用户进行英语对话练习，纠正错误并给出建议。',
    greeting: 'Hello! Let\'s practice English together! What would you like to talk about?',
    icon: 'Languages',
    color: '#8B5CF6',
    is_active: true,
    sort_order: 3,
  },
];

export { users, categories, courses, chapters, aiRoles };
